### ISSUE TITLE
Equation in a different order yields very wrong results

### ISSUE THREAD

**Issue by Pyxidatol-C** [JingjieYang/CHEMaths#10]
https://chemaths.herokuapp.com/?mode=equation&Input=H_2%2BCO_2%5Crightarrow%20C_6H_%7B12%7DO_6%2BH_2O&inputs=%7B%22masses%22%3A%5B%22%22%2C%22%22%2C%22%22%2C%22%22%5D%2C%22moles%22%3A%5B%22%22%2C%22%22%2C%22%22%2C%22%22%5D%7D

https://chemaths.herokuapp.com/?mode=equation&Input=H_2%2BCO_2%5Crightarrow%20C_6H_%7B12%7DO_6%2BH_2O&inputs=%7B%22masses%22%3A%5B%22%22%2C%22%22%2C%22%22%2C%22%22%5D%2C%22moles%22%3A%5B%22%22%2C%22%22%2C%22%22%2C%22%22%5D%7D

**Comment by TrakJohnson** [comment]
wat

**Comment by Pyxidatol-C** [comment]
FLOAT POINT I WILL FIND YOU I WILL KILL YOU
