### ISSUE TITLE
REFACTOR for release

### ISSUE THREAD

**Issue by Pyxidatol-C** [JingjieYang/CHEMaths#11]
Make our website great again!
More precisely: better CSS and better JS (probably react or angular).

Good luck to us.

**Comment by Pyxidatol-C** [comment]
Actually, we also have back-end to refactor too. Time to dispose of linear algebra mess and use numpy.

**Comment by Pyxidatol-C** [comment]
Our (well, my) plan is to make a release for seconde chemistry; that said, it should better be done before the première year begins (2017/09/04). 

The current of our website is at best a *beta* version, if not an *alpha* version. Cleanups and refactors are necessary, especially regarding front-end.

**Comment by TrakJohnson** [comment]
Great gods, the formal tone in your comments scares me... I'll see about that tomorrow

**Comment by Pyxidatol-C** [comment]
Well you have to blame that on my SAT classes, old sport. (Also the Great Gatsby, actually)

**Comment by TrakJohnson** [comment]
Tiens ... maybe I should start the summer reading

**Comment by Pyxidatol-C** [comment]
voila we'll leave it as is
