### ISSUE TITLE
Alkane isomer numbers inaccurate

### ISSUE THREAD

**Issue by Pyxidatol-C** [JingjieYang/CHEMaths#6]
The number of structural isomers of alkanes are only accurate up to 6:

- Heptane is said to have `7` structural isomers, while according to wikipedia  
> Heptane has nine isomers
- Octane is said to have `11` isomers, while 
> Octane has 18 structural isomers

**Comment by JingjieYang** [comment]
Problem identified: `chirality` was not taken into account.

**Comment by Pyxidatol-C** [comment]
In the case of heptane,
only one of 

    C - C - C - C - C - C
        |
        C

    C - C - C - C - C - C
            |
            C

is considered;  
only one of 

    C - C - C - C - C - C
        |
        C
        |
        C

    C - C - C - C - C - C
            |
            C
            |
            C

is considered.

These result in the 2 unaccounted structural isomers.

**Comment by TrakJohnson** [comment]
Useful link: http://oeis.org/A000602 (series we are trying to find, probably better off parsing them off wiki 😈 )

**Comment by Pyxidatol-C** [comment]
no one cares anyways 😈
